namespace BetaSharp.Generators;

/// <summary>
///     The attributes the generator recognises, injected into the compilation rather than
///     hand-written in <c>BetaSharp</c>.
///     <para>
///         Injecting keeps the marker and the code that reads it in one project, so they cannot
///         drift. The consequence is that exactly one assembly may reference this generator: the
///         attributes are <c>public</c>, and two assemblies both emitting them would collide the
///         moment one referenced the other. That is the right constraint anyway — a message type has
///         to exist on both peers, which means it belongs in the shared core.
///     </para>
/// </summary>
internal static class WireAttributeSource
{
    public const string MessageAttributeName = "BetaSharp.Network.Messages.WireMessageAttribute";
    public const string FieldAttributeName = "BetaSharp.Network.Messages.WireFieldAttribute";

    public const string Source = """
        // <auto-generated/>
        #nullable enable

        namespace BetaSharp.Network.Messages;

        /// <summary>
        ///     Marks a partial class deriving from <c>Message</c> for generated serialization.
        ///     <para>
        ///         The generator emits <c>Id</c>, <c>Key</c>, <c>SchemaVersion</c>, <c>Read</c>,
        ///         <c>Write</c> and <c>Size</c> from the <c>[WireField]</c> properties. Emitting all
        ///         three of the serialization members from one traversal is the point: a hand-written
        ///         <c>Size()</c> can silently disagree with <c>Write()</c>, and that disagreement
        ///         shows up as a corrupt stream rather than as an exception.
        ///     </para>
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false)]
        public sealed class WireMessageAttribute : global::System.Attribute
        {
            /// <param name="key">The message's stable identity, as <c>namespace:path</c>.</param>
            public WireMessageAttribute(string key)
            {
                Key = key;
            }

            public string Key { get; }

            /// <summary>Bumped when the payload shape changes. Per type, never global.</summary>
            public int Version { get; set; } = 1;
        }

        /// <summary>
        ///     Marks a property as part of the payload, in declaration order.
        ///     <para>
        ///         Opt-in rather than opt-out. A message may hold state that is not wire state —
        ///         caches, values taken from the envelope — and a scheme that serialised everything
        ///         settable would put them on the wire the moment somebody added one. Requiring the
        ///         attribute means the payload only ever changes when someone writes down that it
        ///         should.
        ///     </para>
        ///     <para>
        ///         <b>Declaration order is the wire order.</b> Reordering two properties changes the
        ///         format, exactly as reordering two lines of a hand-written <c>Write</c> would. The
        ///         generated file lists the order in a comment so that such a change is visible in a
        ///         diff of the generated output rather than only in the source.
        ///     </para>
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Property, Inherited = false)]
        public sealed class WireFieldAttribute : global::System.Attribute
        {
            /// <summary>How the value is encoded. Defaults to the fixed-width big-endian form.</summary>
            public WireEncoding Encoding { get; set; } = WireEncoding.Fixed;

            /// <summary>
            ///     Largest blob this field will accept, for <c>byte[]</c> fields. Zero leaves it
            ///     unbounded.
            ///     <para>
            ///         A length read off the wire decides how much memory this peer allocates, so an
            ///         unbounded one hands that decision to whoever is sending. Declaring the bound
            ///         next to the field is the point: a hand-written reader can forget the check,
            ///         and the omission is invisible until somebody sends a large number.
            ///     </para>
            /// </summary>
            public int MaxLength { get; set; }
        }

        /// <summary>Integer encodings a <c>[WireField]</c> may ask for.</summary>
        public enum WireEncoding
        {
            /// <summary>Fixed-width big-endian, the encoding the legacy packets use.</summary>
            Fixed,

            /// <summary>LEB128. For counts, lengths and IDs, where small values dominate.</summary>
            VarInt,

            /// <summary>LEB128 over a zig-zagged value. For deltas, where small values of either sign dominate.</summary>
            ZigZag,
        }

        """;
}
