using System.Collections.Concurrent;
using System.Diagnostics;
using Microsoft.Extensions.Logging;
using OmniBlock.Entities;
using OmniBlock.Server.Worlds;
using OmniBlock.Util.Maths;
using OmniBlock.Worlds.Chunks;

namespace OmniBlock.Server;

internal class ChunkLoadingQueue
{
    internal const int MaxChunkLoadWorkers = 8;
    internal const int MaxCompletedLoadsPerTick = 8;
    internal const double CompletedLoadBudgetMs = 4.0;

    private readonly ChunkMap _chunkMap;
    private readonly ConcurrentQueue<LoadedChunk> _completedChunks = [];
    // Workers finish in cost order, not distance order: a distant chunk found on disk can beat a
    // nearby chunk that needs generation. Keep completions here until the tick thread can publish
    // them as a near-to-far wavefront.
    private readonly List<LoadedChunk> _readyChunks = [];

    // Every chunk that has been requested but not yet applied — whether it's still sitting in
    // _queue or already being generated by a worker. Populated and read only by the tick thread
    // (Add/Remove/RemovePlayer/ApplyCompletedLoads); workers never touch it, only _queue and
    // _completedChunks, so no lock is needed around it beyond what already guards _queue.
    private readonly Dictionary<long, PendingChunk> _inFlightChunks = [];
    private readonly ILogger<ChunkLoadingQueue> _logger = Log.Instance.For<ChunkLoadingQueue>();

    private readonly PriorityQueue<PendingChunk, float> _queue = new();

    private readonly object _queueLock = new();
    private readonly Thread[] _workers;
    private long _nextSequence;

    public ChunkLoadingQueue(ChunkMap chunkMap)
    {
        _chunkMap = chunkMap;

        // Chunk generation is CPU-heavy and this pool shares the process with eight client mesh
        // workers in single-player. Merely leaving two logical processors free still creates 30
        // loaders on a 32-thread machine, oversubscribing simulation, lighting, rendering and
        // networking. A bounded pool preserves parallel generation without flooding the scheduler.
        var workerCount = GetWorkerCount(Environment.ProcessorCount, chunkMap.SharesProcessWithClient);
        _workers = new Thread[workerCount];
        for (var i = 0; i < workerCount; i++)
        {
            _workers[i] = new Thread(WorkerLoop)
            {
                IsBackground = true,
                Name = $"ChunkLoader-{i}"
            };
            _workers[i].Start();
        }
    }

    internal static int GetWorkerCount(int processorCount, bool sharesProcessWithClient = false) =>
        sharesProcessWithClient
            ? Math.Clamp((processorCount - 2) / 2, 1, MaxChunkLoadWorkers / 2)
            : Math.Clamp(processorCount - 2, 1, MaxChunkLoadWorkers);

    public void Add(int x, int z, ServerPlayerEntity player)
    {
        var hash = ChunkMap.GetChunkHash(x, z);

        lock (_queueLock)
        {
            if (_inFlightChunks.TryGetValue(hash, out var existing))
            {
                existing.AddPlayer(player);
                return;
            }

            var pending = new PendingChunk(hash, x, z, _nextSequence++, player);
            _inFlightChunks[hash] = pending;
            _queue.Enqueue(pending, ToQueuePriority(pending.GetPriority()));
            Monitor.Pulse(_queueLock);
        }
    }

    public void RemovePlayer(ServerPlayerEntity player)
    {
        lock (_queueLock)
        {
            var toDrop = new List<PendingChunk>();
            foreach (var chunk in _inFlightChunks.Values)
            {
                chunk.RemovePlayer(player);
                if (chunk.IsEmpty)
                {
                    toDrop.Add(chunk);
                }
            }

            foreach (var chunk in toDrop)
            {
                DropIfStillQueued(chunk);
            }
        }
    }

    public void Remove(int x, int z, ServerPlayerEntity player)
    {
        var hash = ChunkMap.GetChunkHash(x, z);

        lock (_queueLock)
        {
            if (!_inFlightChunks.TryGetValue(hash, out var chunk))
            {
                return;
            }

            chunk.RemovePlayer(player);
            if (chunk.IsEmpty)
            {
                DropIfStillQueued(chunk);
            }
        }
    }

    /// <summary>
    ///     Caller holds <see cref="_queueLock" />. If a worker hasn't picked the chunk up yet,
    ///     cancels it outright. If one already dequeued it, there is no way to cancel a
    ///     generation in progress — it stays in <see cref="_inFlightChunks" /> and is dropped
    ///     normally once <see cref="ApplyCompletedLoads" /> sees it, just wired to nobody.
    /// </summary>
    private void DropIfStillQueued(PendingChunk chunk)
    {
        if (_queue.Remove(chunk, out _, out _))
        {
            _inFlightChunks.Remove(chunk.Hash);
        }
    }

    public void Tick() => ApplyCompletedLoads();

    public void ReprioritizeAll()
    {
        lock (_queueLock)
        {
            if (_queue.Count == 0) return;
            var queued = _queue.UnorderedItems.Select(static item => item.Element).ToArray();
            _queue.Clear();
            foreach (var pending in queued)
                _queue.Enqueue(pending, ToQueuePriority(pending.GetPriority()));
            Monitor.PulseAll(_queueLock);
        }
    }

    /// <summary>Publishes a bounded batch of chunks completed by background workers.</summary>
    /// <remarks>
    ///     Publication is not a cheap queue drain: inserting a chunk initializes block light and
    ///     may decorate up to four neighbours. Letting a large worker burst run to completion here
    ///     makes simulation and the next chunk-send pass wait behind all of it. The count prevents
    ///     one timer anomaly from admitting an unbounded batch; the wall-clock budget adapts to
    ///     expensive chunks while always allowing at least one item to make progress.
    /// </remarks>
    private void ApplyCompletedLoads()
    {
        while (_completedChunks.TryDequeue(out var completed))
            _readyChunks.Add(completed);

        var started = Stopwatch.GetTimestamp();
        var applied = 0;
        while (applied < MaxCompletedLoadsPerTick &&
               (applied == 0 || Stopwatch.GetElapsedTime(started).TotalMilliseconds < CompletedLoadBudgetMs) &&
               TryTakeNextPublishable(out var loaded))
        {
            var chunkToLoad = loaded.Pending;
            _inFlightChunks.Remove(chunkToLoad.Hash);

            if (loaded.Error is not null)
            {
                // Removing the in-flight marker is the recovery mechanism. ChunkMap will request
                // this position again on a later tick if a player still needs it; retaining the
                // marker would make one failed generation attempt an invisible permanent hole.
                _logger.LogError(loaded.Error,
                    "Failed to load or generate chunk {ChunkX},{ChunkZ}; it may be retried",
                    chunkToLoad.X, chunkToLoad.Z);
                applied++;
                continue;
            }

            var chunkCache = _chunkMap.getWorld().ChunkCache;
            chunkCache.InsertLoadedChunk(chunkToLoad.X, chunkToLoad.Z, loaded.Chunk!);

            var chunk = _chunkMap.GetOrCreateChunk(chunkToLoad.X, chunkToLoad.Z, true);
            if (chunk != null)
            {
                foreach (var player in chunkToLoad.Players)
                {
                    if (!chunk.HasPlayer(player))
                    {
                        chunk.addPlayer(player);
                    }
                }
            }

            applied++;
        }
    }

    /// <summary>
    ///     Takes the highest-priority completed chunk, but only after every closer ring has finished.
    /// </summary>
    /// <remarks>
    ///     Generation remains fully parallel. This gate controls only publication, preventing the
    ///     visible world from developing far-away islands while holes remain around the player.
    ///     Chunks in the same ring retain the movement-direction and age ordering.
    /// </remarks>
    private bool TryTakeNextPublishable(out LoadedChunk loaded)
    {
        loaded = null!;
        if (_readyChunks.Count == 0) return false;

        var bestReadyIndex = 0;
        var bestReadyPriority = _readyChunks[0].Pending.GetPriority();
        for (var i = 1; i < _readyChunks.Count; i++)
        {
            var priority = _readyChunks[i].Pending.GetPriority();
            if (priority.CompareTo(bestReadyPriority) >= 0) continue;
            bestReadyIndex = i;
            bestReadyPriority = priority;
        }

        var nearestOutstandingRing = int.MaxValue;
        foreach (var pending in _inFlightChunks.Values)
            nearestOutstandingRing = Math.Min(nearestOutstandingRing, pending.GetPriority().Ring);

        if (!CanPublishRing(bestReadyPriority.Ring, nearestOutstandingRing)) return false;

        loaded = _readyChunks[bestReadyIndex];
        _readyChunks.RemoveAt(bestReadyIndex);
        return true;
    }

    internal static bool CanPublishRing(int completedRing, int nearestOutstandingRing) =>
        completedRing <= nearestOutstandingRing;

    private void WorkerLoop()
    {
        IChunkSource? generator = null;
        ServerChunkCache? chunkCache = null;

        while (true)
        {
            PendingChunk chunkToLoad;
            lock (_queueLock)
            {
                while (_queue.Count == 0)
                {
                    Monitor.Wait(_queueLock);
                }

                chunkToLoad = _queue.Dequeue();
            }

            // Resolved on first use rather than at thread start: threads are spawned from
            // ChunkMap's constructor, which runs during server startup before loadWorld()
            // populates the world. Nothing can reach this queue before a player exists, and a
            // player can't exist before the world does, so it's always safe by the time we get
            // here.
            chunkCache ??= _chunkMap.getWorld().ChunkCache;
            generator ??= chunkCache.CreateParallelGenerator();

            try
            {
                var chunk = chunkCache.LoadOrGenerateChunkOffThread(chunkToLoad.X, chunkToLoad.Z, generator);
                _completedChunks.Enqueue(new LoadedChunk(chunkToLoad, chunk, null));
            }
            catch (Exception ex)
            {
                // A worker must survive a bad save payload or generator bug. Resolution remains on
                // the tick thread because _inFlightChunks is deliberately single-thread-owned.
                _completedChunks.Enqueue(new LoadedChunk(chunkToLoad, null, ex));
                generator = null;
            }
        }
    }

    // PriorityQueue needs one totally-ordered key; ChunkPriority's Sequence tie-break doesn't
    // fit alongside Ring/DirectionPenalty in a float without risking collisions, so it's
    // dropped here — ties between equally-ranked, equally-aligned requests are broken by
    // whatever order the heap happens to hold them in rather than strict FIFO.
    private static float ToQueuePriority(ChunkPriority priority) =>
        priority.Ring * 1000f + (float)priority.DirectionPenalty;

    private sealed record LoadedChunk(PendingChunk Pending, Chunk? Chunk, Exception? Error);

    private class PendingChunk
    {
        public PendingChunk(long hash, int x, int z, long sequence, ServerPlayerEntity initiator)
        {
            Hash = hash;
            X = x;
            Z = z;
            ChunkPos = new ChunkPos(x, z);
            Sequence = sequence;
            AddPlayer(initiator);
        }

        public long Hash { get; }
        public int X { get; }
        public int Z { get; }
        public ChunkPos ChunkPos { get; }
        public HashSet<ServerPlayerEntity> Players { get; } = [];
        public long Sequence { get; }
        public bool IsEmpty => Players.Count == 0;

        public void AddPlayer(ServerPlayerEntity player) => Players.Add(player);

        public void RemovePlayer(ServerPlayerEntity player) => Players.Remove(player);

        public ChunkPriority GetPriority()
        {
            var hasAny = false;
            ChunkPriority bestPriority = default;

            foreach (var player in Players)
            {
                var candidate = player.GetChunkPriority(ChunkPos, Sequence);
                if (!hasAny || candidate.CompareTo(bestPriority) < 0)
                {
                    bestPriority = candidate;
                    hasAny = true;
                }
            }

            return hasAny
                ? bestPriority
                : new ChunkPriority(int.MaxValue, double.MaxValue, Sequence);
        }
    }
}
