using System.Collections.Concurrent;
using OmniBlock.Entities;
using OmniBlock.Server.Worlds;
using OmniBlock.Util.Maths;
using OmniBlock.Worlds.Chunks;

namespace OmniBlock.Server;

internal class ChunkLoadingQueue
{
    private readonly ChunkMap _chunkMap;

    private readonly PriorityQueue<PendingChunk, float> _queue = new();

    // Every chunk that has been requested but not yet applied — whether it's still sitting in
    // _queue or already being generated by a worker. Populated and read only by the tick thread
    // (Add/Remove/RemovePlayer/ApplyCompletedLoads); workers never touch it, only _queue and
    // _completedChunks, so no lock is needed around it beyond what already guards _queue.
    private readonly Dictionary<long, PendingChunk> _inFlightChunks = [];

    private readonly object _queueLock = new();
    private readonly ConcurrentQueue<LoadedChunk> _completedChunks = [];
    private readonly Thread[] _workers;
    private long _nextSequence;

    public ChunkLoadingQueue(ChunkMap chunkMap)
    {
        _chunkMap = chunkMap;

        // Leave 2 cores for the tick thread and networking — a generation-heavy pool that
        // saturates every core starves the very thread it exists to keep unblocked.
        int workerCount = Math.Max(1, Environment.ProcessorCount - 2);
        _workers = new Thread[workerCount];
        for (int i = 0; i < workerCount; i++)
        {
            _workers[i] = new Thread(WorkerLoop) { IsBackground = true, Name = $"ChunkLoader-{i}" };
            _workers[i].Start();
        }
    }

    public void Add(int x, int z, ServerPlayerEntity player)
    {
        long hash = ChunkMap.GetChunkHash(x, z);

        lock (_queueLock)
        {
            if (_inFlightChunks.TryGetValue(hash, out PendingChunk? existing))
            {
                existing.AddPlayer(player);
                return;
            }

            var pending = new PendingChunk(hash, x, z, _nextSequence++, player);
            _inFlightChunks[hash] = pending;
            _queue.Enqueue(pending, ToQueuePriority(pending.GetPriority()));
            Monitor.Pulse(_queueLock);
        }
    }

    public void RemovePlayer(ServerPlayerEntity player)
    {
        lock (_queueLock)
        {
            var toDrop = new List<PendingChunk>();
            foreach (PendingChunk chunk in _inFlightChunks.Values)
            {
                chunk.RemovePlayer(player);
                if (chunk.IsEmpty)
                {
                    toDrop.Add(chunk);
                }
            }

            foreach (PendingChunk chunk in toDrop)
            {
                DropIfStillQueued(chunk);
            }
        }
    }

    public void Remove(int x, int z, ServerPlayerEntity player)
    {
        long hash = ChunkMap.GetChunkHash(x, z);

        lock (_queueLock)
        {
            if (!_inFlightChunks.TryGetValue(hash, out PendingChunk? chunk))
            {
                return;
            }

            chunk.RemovePlayer(player);
            if (chunk.IsEmpty)
            {
                DropIfStillQueued(chunk);
            }
        }
    }

    /// <summary>
    ///     Caller holds <see cref="_queueLock"/>. If a worker hasn't picked the chunk up yet,
    ///     cancels it outright. If one already dequeued it, there is no way to cancel a
    ///     generation in progress — it stays in <see cref="_inFlightChunks"/> and is dropped
    ///     normally once <see cref="ApplyCompletedLoads"/> sees it, just wired to nobody.
    /// </summary>
    private void DropIfStillQueued(PendingChunk chunk)
    {
        if (_queue.Remove(chunk, out _, out _, null))
        {
            _inFlightChunks.Remove(chunk.Hash);
        }
    }

    public void Tick()
    {
        ApplyCompletedLoads();
    }

    /// <summary>Applies every chunk a background worker has finished loading since the last tick.</summary>
    private void ApplyCompletedLoads()
    {
        while (_completedChunks.TryDequeue(out LoadedChunk loaded))
        {
            PendingChunk chunkToLoad = loaded.Pending;
            _inFlightChunks.Remove(chunkToLoad.Hash);

            ServerChunkCache chunkCache = _chunkMap.getWorld().ChunkCache;
            chunkCache.InsertLoadedChunk(chunkToLoad.X, chunkToLoad.Z, loaded.Chunk);

            ChunkMap.TrackedChunk? chunk = _chunkMap.GetOrCreateChunk(chunkToLoad.X, chunkToLoad.Z, true);
            if (chunk != null)
            {
                foreach (var player in chunkToLoad.Players)
                {
                    if (!chunk.HasPlayer(player))
                    {
                        chunk.addPlayer(player);
                    }
                }
            }
        }
    }

    private void WorkerLoop()
    {
        IChunkSource? generator = null;
        ServerChunkCache? chunkCache = null;

        while (true)
        {
            PendingChunk chunkToLoad;
            lock (_queueLock)
            {
                while (_queue.Count == 0)
                {
                    Monitor.Wait(_queueLock);
                }

                chunkToLoad = _queue.Dequeue();
            }

            // Resolved on first use rather than at thread start: threads are spawned from
            // ChunkMap's constructor, which runs during server startup before loadWorld()
            // populates the world. Nothing can reach this queue before a player exists, and a
            // player can't exist before the world does, so it's always safe by the time we get
            // here.
            chunkCache ??= _chunkMap.getWorld().ChunkCache;
            generator ??= chunkCache.CreateParallelGenerator();

            Chunk chunk = chunkCache.LoadOrGenerateChunkOffThread(chunkToLoad.X, chunkToLoad.Z, generator);
            _completedChunks.Enqueue(new LoadedChunk(chunkToLoad, chunk));
        }
    }

    // PriorityQueue needs one totally-ordered key; ChunkPriority's Sequence tie-break doesn't
    // fit alongside Ring/DirectionPenalty in a float without risking collisions, so it's
    // dropped here — ties between equally-ranked, equally-aligned requests are broken by
    // whatever order the heap happens to hold them in rather than strict FIFO.
    private static float ToQueuePriority(ChunkPriority priority) =>
        priority.Ring * 1000f + (float)priority.DirectionPenalty;

    private sealed record LoadedChunk(PendingChunk Pending, Chunk Chunk);

    private class PendingChunk
    {
        public long Hash { get; }
        public int X { get; }
        public int Z { get; }
        public ChunkPos ChunkPos { get; }
        public HashSet<ServerPlayerEntity> Players { get; } = [];
        public long Sequence { get; }
        public bool IsEmpty => Players.Count == 0;

        public PendingChunk(long hash, int x, int z, long sequence, ServerPlayerEntity initiator)
        {
            Hash = hash;
            X = x;
            Z = z;
            ChunkPos = new ChunkPos(x, z);
            Sequence = sequence;
            AddPlayer(initiator);
        }

        public void AddPlayer(ServerPlayerEntity player)
        {
            Players.Add(player);
        }

        public void RemovePlayer(ServerPlayerEntity player)
        {
            Players.Remove(player);
        }

        public ChunkPriority GetPriority()
        {
            bool hasAny = false;
            ChunkPriority bestPriority = default;

            foreach (var player in Players)
            {
                ChunkPriority candidate = player.GetChunkPriority(ChunkPos, Sequence);
                if (!hasAny || candidate.CompareTo(bestPriority) < 0)
                {
                    bestPriority = candidate;
                    hasAny = true;
                }
            }

            return hasAny
                ? bestPriority
                : new ChunkPriority(int.MaxValue, double.MaxValue, Sequence);
        }
    }
}
